//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirlesikOdeme.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.transactions = new HashSet<transactions>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string IDENTITYNO { get; set; }
        public string IDENTITYNOVERIFIED { get; set; }
        public string MAIL { get; set; }
        public Nullable<System.DateTime> EKLZMN { get; set; }
        public string EKLKLN { get; set; }
        public Nullable<System.DateTime> GNCZMN { get; set; }
        public string GNCKLN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactions> transactions { get; set; }
    }
}
