//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirlesikOdeme.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int ID { get; set; }
        public int CUSTOMERID { get; set; }
        public int ORDERID { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CARDPAN { get; set; }
        public string RESPONSECODE { get; set; }
        public string RESPONSEMESSAGE { get; set; }
        public Nullable<int> STATUSID { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
